micronaut:
  application:
    name: cetitre
  router:
    static-resources:
      static:
        enabled: true
        paths: classpath:cetitre/static
        mapping: /**

endpoints:
  health:
    details-visible: ANONYMOUS

postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: zoo
      user: zoo
      password: zoo
      maxSize: 5

jackson:
  serialization:
    writeDatesAsTimestamps: false